#
# Makefile for building GreenCard example using Cygwin's GNU make and
# ghc-6.00 and GreenCard 3.00 under Linux
#

# site-specific definitions:

# end site-specific definitions

# platform-specific definitions:

# end platform-specific definitions

include Makedefs.ghc